# Generated by Django 5.0.14 on 2025-12-06 14:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='User ID (nullable for Phase 1, required after auth implementation)', null=True)),
                ('title', models.CharField(blank=True, help_text='Conversation title, auto-generated from first message if not set', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Optional conversation settings (e.g., custom system prompt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-last_message_at', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='conversatio_user_id_f1418c_idx'), models.Index(fields=['-created_at'], name='conversatio_created_d82801_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='AI-generated summary of the message range')),
                ('message_range_start', models.PositiveIntegerField(help_text='Starting sequence number of summarized messages')),
                ('message_range_end', models.PositiveIntegerField(help_text='Ending sequence number of summarized messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='chat.conversation')),
            ],
            options={
                'db_table': 'conversation_summaries',
                'ordering': ['-message_range_end'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4000)])),
                ('token_count', models.PositiveIntegerField(blank=True, help_text='Number of tokens in this message', null=True)),
                ('model_used', models.CharField(blank=True, help_text='LLM model used to generate response', max_length=100)),
                ('response_time_ms', models.FloatField(blank=True, help_text='Time taken to generate response in milliseconds', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed'), ('regenerated', 'Regenerated')], db_index=True, default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='Order of message in conversation')),
                ('parent_message_id', models.UUIDField(blank=True, help_text='Parent message ID for regenerated messages', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1-5', null=True)),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment')),
                ('feedback_type', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('report', 'Report'), ('correction', 'Correction')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.message')),
            ],
            options={
                'db_table': 'message_feedback',
            },
        ),
        migrations.CreateModel(
            name='MessageMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_tokens', models.PositiveIntegerField(help_text='Number of tokens in the prompt', null=True)),
                ('completion_tokens', models.PositiveIntegerField(help_text='Number of tokens in the completion', null=True)),
                ('cost', models.DecimalField(decimal_places=6, help_text='Cost of this API call in USD', max_digits=10, null=True)),
                ('finish_reason', models.CharField(blank=True, help_text='Reason for completion (stop, length, etc.)', max_length=50)),
                ('raw_response', models.JSONField(blank=True, help_text='Raw response from LLM API for debugging', null=True)),
                ('latency_breakdown', models.JSONField(blank=True, help_text='Detailed latency metrics', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='chat.message')),
            ],
            options={
                'db_table': 'message_metadata',
            },
        ),
        migrations.AddConstraint(
            model_name='conversationsummary',
            constraint=models.CheckConstraint(check=models.Q(('message_range_start__lt', models.F('message_range_end'))), name='valid_message_range'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='messages_convers_38b855_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sequence_number'], name='messages_convers_87537f_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence_number'), name='unique_sequence_per_conversation'),
        ),
        migrations.AddConstraint(
            model_name='messagefeedback',
            constraint=models.UniqueConstraint(fields=('message', 'feedback_type'), name='unique_feedback_per_type'),
        ),
        migrations.AddConstraint(
            model_name='messagefeedback',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='valid_rating_range'),
        ),
    ]
